<script lang="ts">

	import SelectInput from "./SelectInput.svelte";

  export let selected: string = '';
  export let error: any;

  const countries = [
    { value: "AF", name: "Afeganistão" },
    { value: "AL", name: "Albânia" },
    { value: "DZ", name: "Argélia" },
    { value: "AD", name: "Andorra" },
    { value: "AO", name: "Angola" },
    { value: "AR", name: "Argentina" },
    { value: "AM", name: "Armênia" },
    { value: "AU", name: "Austrália" },
    { value: "AT", name: "Áustria" },
    { value: "AZ", name: "Azerbaijão" },
    { value: "BH", name: "Bahrein" },
    { value: "BD", name: "Bangladesh" },
    { value: "BY", name: "Bielorrússia" },
    { value: "BE", name: "Bélgica" },
    { value: "BZ", name: "Belize" },
    { value: "BJ", name: "Benin" },
    { value: "BT", name: "Butão" },
    { value: "BO", name: "Bolívia" },
    { value: "BA", name: "Bósnia e Herzegovina" },
    { value: "BW", name: "Botsuana" },
    { value: "BR", name: "Brasil" },
    { value: "BN", name: "Brunei" },
    { value: "BG", name: "Bulgária" },
    { value: "BF", name: "Burkina Faso" },
    { value: "BI", name: "Burundi" },
    { value: "CV", name: "Cabo Verde" },
    { value: "KH", name: "Camboja" },
    { value: "CM", name: "Camarões" },
    { value: "CA", name: "Canadá" },
    { value: "CF", name: "República Centro-Africana" },
    { value: "TD", name: "Chade" },
    { value: "CL", name: "Chile" },
    { value: "CN", name: "China" },
    { value: "CO", name: "Colômbia" },
    { value: "KM", name: "Comores" },
    { value: "CG", name: "Congo" },
    { value: "CR", name: "Costa Rica" },
    { value: "HR", name: "Croácia" },
    { value: "CU", name: "Cuba" },
    { value: "CY", name: "Chipre" },
    { value: "CZ", name: "Tchéquia" },
    { value: "DK", name: "Dinamarca" },
    { value: "DJ", name: "Djibuti" },
    { value: "EG", name: "Egito" },
    { value: "SV", name: "El Salvador" },
    { value: "GQ", name: "Guiné Equatorial" },
    { value: "ER", name: "Eritreia" },
    { value: "EE", name: "Estônia" },
    { value: "ET", name: "Etiópia" },
    { value: "FJ", name: "Fiji" },
    { value: "FI", name: "Finlândia" },
    { value: "FR", name: "França" },
    { value: "GA", name: "Gabão" },
    { value: "GE", name: "Geórgia" },
    { value: "DE", name: "Alemanha" },
    { value: "GH", name: "Gana" },
    { value: "GR", name: "Grécia" },
    { value: "GT", name: "Guatemala" },
    { value: "GN", name: "Guiné" },
    { value: "HT", name: "Haiti" },
    { value: "HU", name: "Hungria" },
    { value: "IN", name: "Índia" },
    { value: "ID", name: "Indonésia" },
    { value: "IR", name: "Irã" },
    { value: "IQ", name: "Iraque" },
    { value: "IE", name: "Irlanda" },
    { value: "IL", name: "Israel" },
    { value: "IT", name: "Itália" },
    { value: "JM", name: "Jamaica" },
    { value: "JP", name: "Japão" },
    { value: "JO", name: "Jordânia" },
    { value: "KZ", name: "Cazaquistão" },
    { value: "KE", name: "Quênia" },
    { value: "KW", name: "Kuwait" },
    { value: "KG", name: "Quirguistão" },
    { value: "LA", name: "Laos" },
    { value: "LV", name: "Letônia" },
    { value: "LB", name: "Líbano" },
    { value: "LY", name: "Líbia" },
    { value: "LT", name: "Lituânia" },
    { value: "LU", name: "Luxemburgo" },
    { value: "MG", name: "Madagáscar" },
    { value: "MY", name: "Malásia" },
    { value: "MX", name: "México" },
    { value: "MD", name: "Moldávia" },
    { value: "MN", name: "Mongólia" },
    { value: "ME", name: "Montenegro" },
    { value: "MA", name: "Marrocos" },
    { value: "MZ", name: "Moçambique" },
    { value: "NA", name: "Namíbia" },
    { value: "NP", name: "Nepal" },
    { value: "NL", name: "Países Baixos" },
    { value: "NZ", name: "Nova Zelândia" },
    { value: "NI", name: "Nicarágua" },
    { value: "NG", name: "Nigéria" },
    { value: "NO", name: "Noruega" },
    { value: "OM", name: "Omã" },
    { value: "PK", name: "Paquistão" },
    { value: "PA", name: "Panamá" },
    { value: "PY", name: "Paraguai" },
    { value: "PE", name: "Peru" },
    { value: "PH", name: "Filipinas" },
    { value: "PL", name: "Polônia" },
    { value: "PT", name: "Portugal" },
    { value: "RU", name: "Rússia" },
    { value: "SA", name: "Arábia Saudita" },
    { value: "ZA", name: "África do Sul" },
    { value: "ES", name: "Espanha" },
    { value: "SE", name: "Suécia" },
    { value: "CH", name: "Suíça" },
    { value: "TR", name: "Turquia" },
    { value: "UA", name: "Ucrânia" },
    { value: "GB", name: "Reino Unido" },
    { value: "US", name: "Estados Unidos" }
  ];

</script>
<SelectInput
  options={countries}
  placeholder="Selecione um país"
  bind:selected={selected}
  error={error}
/>